<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\modules\PowerDocu.Common\PowerDocu.Common\PowerDocu.Common.csproj" />
    <ProjectReference Include="..\PowerDocu.AppDocumenter\PowerDocu.AppDocumenter.csproj" />
    <ProjectReference Include="..\PowerDocu.FlowDocumenter\PowerDocu.FlowDocumenter.csproj" />
    <ProjectReference Include="..\PowerDocu.AgentDocumenter\PowerDocu.AgentDocumenter.csproj" />
    <ProjectReference Include="..\PowerDocu.AppModuleDocumenter\PowerDocu.AppModuleDocumenter.csproj" />
    <ProjectReference Include="..\PowerDocu.AIModelDocumenter\PowerDocu.AIModelDocumenter.csproj" />
    <ProjectReference Include="..\PowerDocu.BPFDocumenter\PowerDocu.BPFDocumenter.csproj" />
    <ProjectReference Include="..\PowerDocu.ClassicWorkflowDocumenter\PowerDocu.ClassicWorkflowDocumenter.csproj" />
    <ProjectReference Include="..\PowerDocu.DesktopFlowDocumenter\PowerDocu.DesktopFlowDocumenter.csproj" />
    <ProjectReference Include="..\PowerDocu.DataflowDocumenter\PowerDocu.DataflowDocumenter.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <DebugType>embedded</DebugType>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="Resources\*.*">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
    </Content>
  </ItemGroup>
</Project>
