<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="CommandLineParser" Version="2.9.1" />
    <PackageReference Include="Fontawesome.sharp" Version="6.6.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PowerDocu.FlowDocumenter\PowerDocu.FlowDocumenter.csproj" />
    <ProjectReference Include="..\PowerDocu.AppDocumenter\PowerDocu.AppDocumenter.csproj" />
    <ProjectReference Include="..\PowerDocu.SolutionDocumenter\PowerDocu.SolutionDocumenter.csproj" />
    <Content Include="Icons\*.*">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
    </Content>
    <Content Include="lib\*.*">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <ExcludeFromSingleFile>false</ExcludeFromSingleFile>
    </Content>
  </ItemGroup>
  <PropertyGroup>
    <Version>2.4.1</Version>
    <Copyright>Rene Modery</Copyright>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <LangVersion>latest</LangVersion>
    <UseWindowsForms>true</UseWindowsForms>
    <ApplicationIcon>Icons\PowerDocu.ico</ApplicationIcon>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <PublishSingleFile>true</PublishSingleFile>
    <DebugType>embedded</DebugType>
    <AssemblyName>PowerDocu</AssemblyName>
  </PropertyGroup>


<!-- newer versions of glib and gobject as older versions that are part of graphviz have a vulnerability-->
<!-- After build: copy from lib\ to build root -->
<Target Name="CopyDllsToRootAfterBuild" AfterTargets="Build">
  <ItemGroup>
    <DllsToCopy Include="$(OutputPath)lib\glib-2.dll" />
    <DllsToCopy Include="$(OutputPath)lib\gobject-2.dll" />
  </ItemGroup>

  <Copy SourceFiles="@(DllsToCopy)" DestinationFolder="$(OutputPath)" SkipUnchangedFiles="true" />
</Target>

<!-- After publish: copy from lib\ to publish root -->
<Target Name="CopyDllsToRootAfterPublish" AfterTargets="Publish">
  <ItemGroup>
    <DllsToCopy Include="$(OutputPath)lib\glib-2.dll" />
    <DllsToCopy Include="$(OutputPath)lib\gobject-2.dll" />
  </ItemGroup>

  <Copy SourceFiles="@(DllsToCopy)" DestinationFolder="$(PublishDir)" SkipUnchangedFiles="true" />
</Target>


</Project>